### ISSUE TITLE
How do I merge pthread.cpp with codec?

### ISSUE THREAD

**Issue by Jamaika1** [ultravideo/uvg266#4]
I wonder what are pthread.cpp and semaphore.cpp for?
I compiled the add-ons in C++11 and was unable to merge the codec.
I had to use libpthread. Is that good thinking?

**Comment by fador** [comment]
The built-in pthread wrapper is only used in windows (visual studio environment), where there's no native pthreads library available.
We also have it as a separate repo: https://github.com/ultravideo/ThreadWrapper

The reason is that we got annoyed with the fact that you needed to fetch a 3rd party library in order to build our encoder 😅

So overall, if the pthread library is available (like in linux, unix, mingw) the pthread.cpp and semaphore.cpp should not be used.

**Comment by Jovasa** [comment]
uvg266 uses pthreads, which is present in any Unix based platform (including MinGW and derivatives) but not on native Windows which is why we created https://github.com/ultravideo/ThreadWrapper as a minimal implementation of pthreads so that we no longer needed a third party dependency to a pthreads library. 

If you are on Unix based system you should use the platform supplied pthreads.

**Comment by fador** [comment]
In practice we have only used our built-in pthread wrapper with visual studio like the CMakeLists.txt does currently: https://github.com/ultravideo/uvg266/blob/master/CMakeLists.txt#L119

**Comment by Jamaika1** [comment]
I already know what I didn't know.
I used c11. Should be c++11 for library merge
```
c:/msys1201/bin/../lib/gcc/x86_64-w64-mingw32/12.0.1/../../../../x86_64-w64-mingw32/bin/ld.exe: pthread.o:pthread.cpp:(.xdata+0x94): undefined reference to `__gxx_personality_seh0'
```
